//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Squad
    {
        public long SlNo { get; set; }
        public int TeamID { get; set; }
        public int PlayerID { get; set; }
        public long Year { get; set; }
    
        public virtual PlayerDetail PlayerDetail { get; set; }
        public virtual TeamMaster TeamMaster { get; set; }
    }
}
